### ISSUE TITLE
SIARD2.2 Inquiry

### ISSUE THREAD

**Issue by galanthusya** [sfa-siard/siard-suite#102]
Is there SIARD2.2 packing(install) source?
SIARD2.2 packing(install), ERASER_GUI Are you willing to open it?
If you are willing to open, when will it be possible?
Is the current SIARD2.2 source complete and compilable?
SIARD2.2 Has only the design changed or has the source code also changed?

**Comment by mburri** [comment]
@galanthusya 
I'm not sure if I understand your question.
The new SIARD Suite 2.2. (GUI Application) was implemented last year and its source code is open.
The design and source code changed (compared to Siard GUI (Siard 2.1)) but the underlying libraries (siardapi, siardcmd etc.) are basically the same.

We will probably migrate the dependencies from ant to gradle in the future. It's already done for some of the dependencies.
