### ISSUE TITLE
Getting beyond the 50th record

### ISSUE THREAD

**Issue by audunlund** [sfa-siard/siard-suite#61]
Hello,
When examining a SIARD File, getting beyond the 50th record entry is just possible by using the mouse wheel. This should also be possible by using the scrollbar and the keyboard.
Thanks in advance.
Best regards
Audun
![Scroll](https://github.com/sfa-siard/siard-suite/assets/51159584/d80a4be9-6ef0-40de-89a6-c06657fed2ab)

**Comment by sdbuehlmann** [comment]
Hi @audunlund, thanks for your report. We will look into that and will come back to you. Thanks for your patience.

**Comment by sfa-siard** [comment]
solved with version 2.2.140
