### ISSUE TITLE
SIARD Suite is installed in folder “Unknown” on Windows

### ISSUE THREAD

**Issue by audunlund** [sfa-siard/siard-suite#62]
Hello,
I was searching for Siard Suite in the Start menu but couldn’t find it until I was opening the sub-folders where I finally found it under the folder name “Unknown”.

See attached picture files for illustrations.

Best regards
Audun Lund

![unknown1](https://github.com/sfa-siard/siard-suite/assets/51159584/b81e2813-a9c1-4e77-a09f-1fd447240f10)
![unknown2](https://github.com/sfa-siard/siard-suite/assets/51159584/784dd022-8b36-415f-89ef-7e4e08bff0b9)

**Comment by mburri** [comment]
@audunlund 

I've just confirmed the problem. A few more details:

The installation location can be chosen when installing the suite (I used the msi-installer):

![image](https://github.com/sfa-siard/siard-suite/assets/4577216/0a10ddad-de3d-4cb0-b684-a48b696c4045)

But this is where the binary files are placed.
The application shortcut is then created by the installer in a folder called "Unknown":

![image](https://github.com/sfa-siard/siard-suite/assets/4577216/1d1345c7-670e-4e04-b000-d464ff13fd18)

We need to see how we can control this behavior. We obviously did not implement the installer ourselves. We need to look into that.

For now, you can move the SIARD application shortcut manually to another location if you wish.

**Comment by sdbuehlmann** [comment]
Hi @audunlund (or @mbangerter),

The problem is a simple misconfiguration of the specific build step. What is your preference for the naming of this folder/group? It could be something simple like "SIARD" (for grouping all SIARD dependent tools), or sometimes the company name is used. What would you prefer?

**Comment by mbangerter** [comment]
Hello, 
what about the repo name "SFA-SIARD"?

**Comment by sdbuehlmann** [comment]
Finally named the group "SIARD Suite" because of [this](https://github.com/sfa-siard/siard-suite/commit/fdb14253d7a4bec7d5b4ea587dbfe1ae23a24a78#commitcomment-136219934) comment by @mbangerter.

**Comment by sfa-siard** [comment]
solved with version 2.2.140
