### ISSUE TITLE
Establish connection to MS Access database

### ISSUE THREAD

**Issue by mbangerter** [sfa-siard/siard-suite#64]
When archiving an MS Access database it is currently not possible to establish a connection without some dummy input for the individual fields, see screenshot below.
This should be possible.

![31-10-2023_13-35-08](https://github.com/sfa-siard/siard-suite/assets/149482480/83919667-3ba4-4420-9df4-2abbc2034d29)

Best regards
Maya

**Comment by sdbuehlmann** [comment]
Hi @mbangerter, thank you for your report! You are right; the current mask does not fully meet the requirements of Access databases. As you mentioned, having to provide dummy data to satisfy form validation is not the most user-friendly way to establish a connection, but it is a valid workaround for now.

We will look into your change request and get back to you. Thanks for your patience.

**Comment by sdbuehlmann** [comment]
Implemented own mask for establishing JDBC connection to a Microsoft Access file. A file chooser can be opened through clicking on the icon in the file field.

![Image](https://github.com/sfa-siard/siard-suite/assets/27723543/416ef0ba-53d4-4a38-9e0b-0137771bcf7b)

**Comment by sfa-siard** [comment]
solved with version 2.2.140
