### ISSUE TITLE
Entry `mimeType` for a colum of type BLOB

### ISSUE THREAD

**Issue by oschihin** [sfa-siard/siard-suite#90]
A SIARD file created with SIARD Suite 2.2.141 contains BLOBS in two separate columns. The binary objects are mostly PDF, DOCX, and some JPG and PNG, few others, with their regular file endings (no `.*bin`).

In `metadata.xml`, the columns have a `mimeType`, i.e.
```xml
<column>
   <name>DokumentInhalt</name>
   <type>BLOB</type>
   <mimeType>application/pdf</mimeType>
   <typeOriginal>image</typeOriginal>
 </column>
```
This is obviously wrong for more than half of the files. When opening this files through SIARD suite, it opens up the corresponding viewer (Acrobat reader), even if it is a `*.docx`

Question:
* Is there an option to suppress the writing of this optional field when file endings are have a corresponding mime type and are not normalised?
* When opening the files through SIARD suite, should not first the file ending be checked, before a fallback to this field?

**Comment by mburri** [comment]
@oschihin 
This is a good catch! 
There is currently no option to suppress writing the mime type.

Without knowing the details: I assume that the mime type of the last (or first) file wins and is written to the columns meta data in the siard archive.

But that is incorrect if there are various file types stored in the column. But there won't be a file ending in a blob - this is just binary data. But I think it should be possible to determine the mime type at runtime. 

I wonder if this scenario is covered by the SIARD specification - we'll have to check that.

**Comment by mburri** [comment]
I just checked the official specification. The relevant part is:

```
MIME type of this column, if it is a BLOB column and all records contain files of the
same MIME type in this column. This purely advisory element helps choosing the
correct viewer for binary objects. It can be filled in manually or by the downloading
program, which uses some format recognition mechanism.
```
Source: https://siard.dilcis.eu/SIARD%202.2/SIARD%202.2.pdf (p. 29)

That means that we have to change our implementation:
* if the values stored in a column are of more than one MIME type, we should not detect the mime type and store it in the metadata 

Detect the mime type of a blob at runtime instead of using the value in the column meta data.

**Comment by oschihin** [comment]
I read the same thing, thanks for checking.
Do you know in which timeframe you are able to release a change? We are in the midst of a delivery. Either we wait or we probably have to delete the entrys in that field manually.

**Comment by mburri** [comment]
The fix will make it into the next release. I assume this will be in a few days.
